### ISSUE TITLE
Client commitments for Sprint 1

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#117]
During our meeting with the client Adi, we decided on several things to deliver until Sprint 1 is over : 

 - [x]  A working website with basic functionality
 - [x]  A working plugin with an easy installation from the eclipse marketplace #107 #123 
 - [x] Enable Google crawling for our website - The result should be that searching google for a stack-trace should point to us. #113 #127 #129
 - [x]  Working use-cases - showcasing the capabilities of our product. #91

We should check out all these point until the end of the sprint.

**Comment by yonzarecki** [comment]
Currently, enabling google crawling is impossible as we still don't have an open constant access to the faculty server. Marking as done for now..

**Comment by mdoron** [comment]
## Known bugs
 * In plugin, package name cannot contain "."

**Comment by mdoron** [comment]
### Known Bugs
* Plugin bug: Source directory must be "src" and cannot be yet "src/*", for example: "src/main/java" is not valid.

**Comment by yonzarecki** [comment]
Any more known bugs that you guys know about ? 
@AmitOhayon @tonylekhtman @rodedzats @yosefraisman @ZivIzhar
