### ISSUE TITLE
Website Wishlist

### ISSUE THREAD

**Issue by yonzarecki** [TechnionYP5777/Bugquery#77]
## Website Wishlist
As we decided in our group meeting, @rodedzats, @AmitOhayon and myself, have decided on the following list of objectives for the website.

This list is ordered by priority.

- [x] Move the website to the [bootstrap](http://getbootstrap.com/) platform (developed by twitter), while keeping the old website design. #81 
- [x] Add like\dislike options to existing questions and answers . #82 
- [x] Add loading screen, the screen will also keep track of how long it takes to load a page (will be used to measure the site's performance). #70 
- [x] Add user suggestion for question (with\without answers from other sites). PASSED
- [x] Add comments to question\answers . PASSED
- [x] Add cache functionality of previous results in order to load pages faster, with an option to refresh the results (while querying the DB). #116 
- [x] Add User profiles to the site. PASSED
- [x] Add to the welcome page a list of popular/hot questions.

In order to achieve this goals we'll need to research several things:

- [x] The [bootstrap](http://getbootstrap.com/) platform.
- [x] How forms work in websites to see how we can include the loading page.
- [x] How google's crawler works and how we can let google crawl our site effectively, which in turn will result in more users seeing us in google and using the site. #113
